_format_version: "1.1"

consumers:
  - username: anon
    keyauth_credentials:
      - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
  - username: service_role
    keyauth_credentials:
      - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU

acls:
  - consumer: anon
    group: anon
  - consumer: service_role
    group: service_role

services:
  - name: auth-v1-open
    url: http://auth:9999/verify
    plugins:
      - name: cors
  - name: auth-v1-open-callback
    url: http://auth:9999/callback
    plugins:
      - name: cors
  - name: auth-v1-open-authorize
    url: http://auth:9999/authorize
    plugins:
      - name: cors

  - name: auth-v1
    url: http://auth:9999/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - anon
            - service_role

  - name: rest-v1
    url: http://rest:3000/
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:3000
            - http://localhost:5173
            - http://localhost:5174
            - http://localhost:8084
            - http://localhost:8085
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Encoding
            - Authorization
            - Content-Encoding
            - Content-Length
            - Content-Type
            - Date
            - Host
            - Origin
            - Referer
            - User-Agent
            - X-Requested-With
            - apikey
            - x-client-info
          exposed_headers:
            - Content-Length
            - Content-Range
            - X-Content-Range
          credentials: true
          max_age: 300
      - name: key-auth
        config:
          hide_credentials: true
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - anon
            - service_role

  - name: realtime-v1
    url: http://realtime:4000/socket
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:3000
            - http://localhost:5173
            - http://localhost:5174
            - http://localhost:8084
            - http://localhost:8085
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - anon
            - service_role

routes:
  - service: auth-v1-open
    methods: [GET, POST]
    paths: [/auth/v1/verify]
    strip_path: true

  - service: auth-v1-open-callback
    methods: [GET, POST]
    paths: [/auth/v1/callback]
    strip_path: true

  - service: auth-v1-open-authorize
    methods: [GET, POST]
    paths: [/auth/v1/authorize]
    strip_path: true

  - service: auth-v1
    paths: [/auth/v1/]
    strip_path: true

  - service: rest-v1
    paths: [/rest/v1/]
    strip_path: true

  - service: realtime-v1
    paths: [/realtime/v1/]
    strip_path: true
